RedHatInsights/digital-roadmap-backend

.gitignore
Makefile

Improve Makefile to avoid re-creating targets which are already created.

Fix Makefile targets

---

.gitignore
Containerfile
Makefile

Add containerfile and `make` target to build application in a container.

[RSPEED-368] Build application in container

---

app/config.py

This reflects changes made to the database container image.
Change database environment variables prefixes to be implementation agnostic.

Change default database name

---

.pre-commit-config.yaml

Add switch --fix for ruff which enables automated fixes of code.

Add --fix for ruff

---

app/data/modules.py

Use dates from lifecycle-defs when available. Otherwise fall back to using start/end dates based on the operating system.
When a stream was not present in lifecycle-defs, "Unknown" was put in for start/end dates.

Update app stream lifecycle data

---

.tekton/pull_request.yaml
.tekton/push.yaml

Change image repo

---

requirements.txt
requirements/requirements-3.12.txt
requirements/requirements-3.13.txt
requirements/requirements.in
src/roadmap/main.py
tests/test_main.py

Very basic metrics endpoint. We can configure later as needed.
[RSPEED-468](https://issues.redhat.com/browser/RSPEED-429)

[RSPEED-468] Add Prometheus exporter

---

src/roadmap/v1/lifecycle/systems.py
tests/v1/lifecycle/test_systems.py

In the frontend is more useful to return the data in reverse order.

Reverse system order

---

Containerfile
Makefile

This makes logging easier to control and more consistent.

[RSPEED-622] Run the application using uvicorn

---

Makefile
requirements.txt
requirements/requirements-3.12.txt
requirements/requirements-3.13.txt
requirements/requirements.in
src/roadmap/config.py
src/roadmap/database.py

Require a `ROADMAP_` prefix for environment variables.

Use Pydantic settings for config

---

.gitignore
README.md
scripts/get-redhat-access-token.py
scripts/query_inventory.py

Update README and ignored files

Add tools for generating token and querying inventory

---

Containerfile
Makefile
README.md
deploy/config.yml

This requires some secrets that I have not yet created.
There are probably some other things I'm missing is here as well.

Add OpenShift template for deployment

---

deploy/config.yml

Updating secrets to match what is in Vault.

[RSPEED-627] Update secret refs

---

Containerfile
Makefile
README.md
deploy/config.yml

It must be port 8000 per Clowder requirements.

Change listen port

---

.github/workflows/ci.yml
.tekton/pull_request.yaml
.tekton/push.yaml

AppSRE only allows a small number of branch names for deployment.

Change branch name to main

---

src/roadmap/data/app_streams.py

This will make it possible to use application stream name when building the results.

[RSPEED-828] Add application stream names to modules

---

.tekton/pull_request.yaml
.tekton/push.yaml

Update pipeline name and git repo.

[RSPEED-895] Update pipelines

---

src/roadmap/models.py
src/roadmap/v1/lifecycle/app_streams.py
tests/test_models.py
tests/v1/lifecycle/test_app_streams.py

https://issues.redhat.com/browse/RSPEED-600

[RSPEED-600] Calculate support status

---

deploy/config.yml
scripts/replication.py

- Pull in upstream changes
- Correct database parameter
- Add host-inventory as a dependency

[RSPEED-914] Update replication

---

src/roadmap/data/app_streams.py
src/roadmap/v1/lifecycle/app_streams.py
tests/v1/lifecycle/test_app_streams.py

Pass along app stream package and module dates if available.
Improve logging for missing items.

Fix app stream dates

---

src/roadmap/common.py
src/roadmap/v1/lifecycle/app_streams.py
src/roadmap/v1/lifecycle/rhel.py
tests/conftest.py
tests/v1/lifecycle/test_app_streams.py
tests/v1/lifecycle/test_rhel.py

This should help improve responsiveness and performance.

Stream results from the database

---

src/roadmap/common.py

Return statement is needed otherwise the query for the inventory is reached and results in Server Error.

Fix query host when ROADMAP_DEV set

---

src/roadmap/v1/lifecycle/rhel.py

Emit one summary log message instead of one per event. Keep individual log messages for missing RHEL versions.

Make RHEL logging a bit less noisy

---

tests/test_common.py

Actually query the database during testing and examine the results.

Update all tests marked xfail

---

scripts/replication.py

The hope is that this will resolve replication issues..

Set primary key field when creating hosts table

---

src/roadmap/common.py
src/roadmap/data/app_streams.py
src/roadmap/v1/lifecycle/app_streams.py
tests/test_config.py
tests/v1/lifecycle/test_app_streams.py

`relevant/lifecycle/app-streams` shows which systems are relevant to each app stream

[RSPEED-775] Return system IDs for relevant systems

---

pyproject.toml
src/roadmap/v1/lifecycle/app_streams.py
src/roadmap/v1/lifecycle/rhel.py

Increase minimum complexity setting to 12.

Enable check for unused noqa statements

---

scripts/load_host_data.py

Generate a consistent set of random hostnames.

Improve hostnames used in test host data

---

src/roadmap/common.py

Now that we have metrics working, this is filling up the logs

Filter out /metrics logs

---

dashboards/grafana-dashboard-digital-roadmap-slo.configmap.yaml

This patch introduces a first attempt at SLO dashboards for DR.

[RSPEED-1049] Add SLO dashboards for DR

---

.tekton/pipeline-build.yaml
Containerfile
Makefile

Set `SOURCE_DATE_EPOCH` on build.

Update labels in container image to include cpe and creation date
