RedHatInsights/digital-roadmap-backend

app/crud.py
app/models.py
app/v1/released/endpoints.py

Only return results matching the supplied keywords.
```
python
def send_request():
try:
response = requests.get(
url="http://localhost:8081/api/digital-roadmap/v1/release-notes/get-relevant-notes/",
params={
"keywords": "security,dns,selinux",
"major": "9",
"minor": "5",
},
)
print('Response HTTP Status Code: {status_code}'.format(
status_code=response.status_code))
print('Response HTTP Response Body: {content}'.format(
content=response.content))
except requests.exceptions.RequestException:
print('HTTP Request failed')
```

Add support for filtering release notes based on multiple keywords

---

.codecov.yml

Add repo-scoped token so PRs from forks can reliably upload coverage reports.

Add CodeCov config

---

.github/workflows/unit-tests.yml
Makefile
README.md
app/config.py

Pull a pre-built database container.
Add variables for database image and port for easy overrides.
Detect container runtime with different precedence based on OS.

Make it easier to run the database

---

app/main.py
app/tests/conftest.py
app/tests/test_main.py

Needed for liveness checks once we deploy.

Add ping API

---

app/data/systems.py
app/main.py
app/tests/lifecycle/systems/test_systems.py
app/v1/lifecycle/router.py
app/v1/lifecycle/systems/endpoints.py

Add endpoint for returning RHEL systems start/end dates
TODO:

[RSPEED-427] Add systems endpoint

---

Makefile
README.md

Include necessary packages and configuration for Linux and macOS.
Make environment setup tasks more resilient by finding the system Python once checking for both `python` and `python3`.

Update setup docs

---

Containerfile
requirements.txt
requirements/requirements-3.12.txt
requirements/requirements-3.13.txt
requirements/requirements.in

Perform a [local installation](https://www.psycopg.org/psycopg3/docs/basic/install.html#local-installation) of `psycopg`.
Use a multi-stage build to keep the final container image size down.
```
> docker image ls -f reference='digital-roadmap'
REPOSITORY        TAG       IMAGE ID       CREATED         SIZE
digital-roadmap   latest    1de2178c1830   4 minutes ago   266MB
```

Correctly install psycopg

---

src/roadmap/main.py
src/roadmap/v1/__init__.py
src/roadmap/v1/lifecycle/__init__.py
src/roadmap/v1/lifecycle/app_streams.py
src/roadmap/v1/lifecycle/systems.py
src/roadmap/v1/release_notes.py
src/roadmap/v1/upcoming.py

This makes things much more hierarchical and simplifies the imports at the main application level.

Use module names instead of aliases for routes

---

src/roadmap/main.py
src/roadmap/v1/lifecycle/__init__.py
src/roadmap/v1/lifecycle/app_streams.py
src/roadmap/v1/lifecycle/rhel.py
src/roadmap/v1/release_notes.py
src/roadmap/v1/upcoming.py
tests/test_main.py
tests/v1/conftest.py
tests/v1/lifecycle/test_rhel.py

- Change “digital-roadmap” to “roadmap”
- Change “systems” to “rhel”
- Update documentation tags for better grouping and presentation
Here are the new APIs:
```
[
"/metrics",
"/api/roadmap/v1/lifecycle/app-streams/",
"/api/roadmap/v1/lifecycle/app-streams/{major_version}",
"/api/roadmap/v1/lifecycle/app-streams/{major_version}/names",
"/api/roadmap/v1/lifecycle/app-streams/{major_version}/{module_name}",
"/api/roadmap/v1/lifecycle/rhel/",
"/api/roadmap/v1/lifecycle/rhel/{major}",
"/api/roadmap/v1/lifecycle/rhel/{major}/{minor}",
"/api/roadmap/v1/release-notes/",
"/api/roadmap/v1/upcoming-changes/",
"/api/roadmap/v1/ping"
]
```

Streamline API paths and documentation

---

src/roadmap/v1/__init__.py
src/roadmap/v1/lifecycle/app_streams.py
tests/fixtures/inventory_response.json
tests/v1/lifecycle/test_app_streams.py

This is returning the same data as `/api/roadmap/v1/lifecycle/app-streams/` for now so that UI work can continue.
I added response models for the app streams responses to solidify things a bit.
```
http localhost:8081/api/roadmap/v1/relevant/lifecycle/app-streams/
```

[RSPEED-580] Add relevant app stream API

---

src/roadmap/v1/lifecycle/app_streams.py

Rolling app stream modules are still available from `/api/roadmap/v1/lifecycle/app-streams/`.

[RSPEED-827] Omit rolling app streams from relevant response

---

requirements/requirements-replication-3.12.txt
requirements/requirements-replication-3.13.txt
requirements/requirements-replication.in
scripts/replication.py

Remove psycopg2 from requirements.
Change database URI so that the DBAPI is explicitly set to psycopg.

Use psycopg (version 3) for database connection

---

Containerfile

Trust all IPs in order to preserve forwarding headers correctly.
https://www.uvicorn.org/deployment/#proxies-and-forwarded-headers

[RSPEED-907] Fix 307 redirects

---

Makefile
README.md

Change default virtual environment name, database container name, and name of the application container image.
This will required recreating the default virtual environment and manually cleaning up the old one.
```
[docker|podman] stop digital-roadmap-data
rm -rf .venvs/digital_roadmap
make install-dev
make start-db
```

Remove 'digital-' prefix from make tasks

---

src/roadmap/main.py
src/roadmap/v1/lifecycle/app_streams.py
src/roadmap/v1/lifecycle/rhel.py
src/roadmap/v1/release_notes.py
src/roadmap/v1/upcoming.py
tests/v1/lifecycle/test_app_streams.py
tests/v1/test_upcoming.py

Despite my best efforts, I have not found a way to redirect to the correct hostname. It always redirects to the internal hostname, which is obviously not helpful.
Instead, change APIs to not have a trailing slash and disable automatic 307 redirects. This means a 404 will be returned for API requests with a trailing slash.

[RSPEED-907] Do not redirect trailing slashes

---

src/roadmap/v1/lifecycle/app_streams.py

The data weren't set anywhere which resulted in mising graph in web UI.
TODO:
- add the dates also for the `APP_STREAM_MODULES`. The date needs to be found based on the
`dnf_module["name"], dnf_module["stream"]` which should be unique key for getting date.

[RSPEED-963] Add start and end dates for packages

---

src/roadmap/common.py
src/roadmap/v1/lifecycle/app_streams.py
src/roadmap/v1/lifecycle/rhel.py

Go back to streaming the results from the database.
I needed to yield a single item from FastAPI's dependency injection machinery and do the `mappings()` call in the path function.
Depends on #118

Get database streaming working again

---

deploy/config.yml

Reduce name duplication since Clowder creates items with an app name prefix.
This may break the 3Scale connectivity.

Rename API deployment

---

src/roadmap/common.py
src/roadmap/v1/lifecycle/app_streams.py
src/roadmap/v1/lifecycle/rhel.py

Trying to make the relevant API work with both query and path parameters
got really messy. Rather than fighting it, just go with query parameters
only for the relevant APIs.

[RSPEED-730] Remove path params for /relevant/ API endpoints

---

src/roadmap/data/app_streams.py
src/roadmap/v1/lifecycle/app_streams.py
tests/v1/lifecycle/test_app_streams.py

This is a field with normalized capitalization that handles many special cases and ensures a version number is present at the end.
Remove `stream` from the response schema since it is no longer available on the collated results.

[RSPEED-828] Add a display_name field to relevant app stream results

---

src/roadmap/v1/lifecycle/app_streams.py

FreeRADIUS and OpenJDK needed a special case. Identity Management Client uses a value for `stream` than is not a digit. To avoid duplicating the version in the display name, compare the end of the string in lowercase.

Handle a few more special cases for app stream names

---

tests/conftest.py

`ROADMAP_DEV` is never meant to be set globally during a test run. Add a fixture to unset it for all tests. Tests are still able to set environment variables if needed.
This could also be inverted to a list of environment variables to _allow_ in the testing environment. Starting simple, though.
<details>
<summary>Example test run</summary>
```
> ROADMAP_DEV=1 pytest
/Users/sdoran/.pyenv/versions/3.12.9/envs/dr-backend-3.12.9/lib/python3.12/site-packages/pytest_asyncio/plugin.py:217: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default …
```

[RSPEED-1144] Unset certain environment variables during testing

---

pyproject.toml

This fixes missing coverage in some of our code.

Capture coverage data for all relevant concurrency types

---

src/roadmap/models.py
tests/test_models.py

This makes the API response consistent with recent changes to the app streams API.

Add `display_name` to RHEL lifecycle response

---

src/roadmap/config.py
tests/conftest.py
tests/test_config.py
tests/v1/test_upcoming.py

Environment variables now override Clowder config items for database settings. Hopefully this is a temporary change since database parameters and RBAC parameters now have a different precedence order.

[RSPEED-1232] Change settings precedence

---

deploy/config.yml

Since we need to use the read replica, we cannot use the values provided by the Clowder generated config file.

[RSPEED-1232] Get database configuration from environment variables

---

src/roadmap/models.py
src/roadmap/v1/lifecycle/rhel.py
tests/v1/lifecycle/test_rhel.py

This makes the `/api/roadmap/v1/relevant/lifecycle/rhel` match the behavior of `/api/roadmap/v1/relevant/lifecycle/app-streams`.
<details>
<summary>Example output</summary>
```
> http localhost:8000/api/roadmap/v1/relevant/lifecycle/rhel
{
"meta": {
"count": 20,
"total": 81
},
"data": [
{
"name": "RHEL",
"display_name": "RHEL 9.6",
"major": 9,
"minor": 6,
"release_date": "2025-05-15",
"retirement_date": "2025-11-30",
"support_status": "Upcoming release",
"count": 2,
"lifecycle_type": "mainline",
"related": false,
"systems": [
"22fdb977-29f7-4b7c-9e11-1abe299edb4c",
"ead7f218-4b43-4a7c-9006-dd49a73961b2"
]
},
{
"name": "RHEL",
"display_name": "RHEL 9.5",
"major": 9,
"minor": 5,
"release_date": "2024-11-12",
"retirement_date": "2025-05-31",
"support_status": "Support ends within 6 months", …
```

[RSPEED-1234] Return system IDs from relevant RHEL API

---

README.md
scripts/load_host_data.py

Create a custom host inventory file for testing and load it by setting `ROADMAP_HOST_DATA_FILE` to the path to that file.

Make it easy to load custom host inventory data

---

Containerfile

Instead of silently including an invalid file, fail the build.
The `develop` branch went away in the data repo. Update to the correct ref.

Faild build when data file is unavailable

---

deploy/config.yml
src/roadmap/config.py
src/roadmap/database.py
tests/test_common.py

The database _engine_ should be created only once and reused for the life of the application. The _session_ should be opened and closed for each API request.
Add two new settings for controlling the connection pool size, `ROADMAP_DB_POOL_SIZE`, and the maximum number of connections that can be created, `ROADMAP_DB_MAX_OVERFLOW`. The total number of connections is `pool_size` + `max_overflow`. After that, SQLAlchemy will raise errors.
https://fastapi.tiangolo.com/tutorial/sql-databases/
https://docs.sqlalchemy.org/en/20/errors.html#error-3o7r

[RSPEED-1454] Improve database engine creation and make pool size configurable

---

src/roadmap/common.py
tests/v1/lifecycle/test_app_streams.py

We were rejecting requests when RBAC was returning permissions like this:
```[{'permission': 'inventory:hosts:write', 'resourceDefinitions': []},
{'permission': 'inventory:hosts:read', 'resourceDefinitions': []},
{'permission': 'inventory:groups:write', 'resourceDefinitions': []},
{'permission': 'inventory:groups:read', 'resourceDefinitions': []},
{'permission': 'inventory:groups:read',
'resourceDefinitions': [{'attributeFilter': {'key': 'group.id',
'operation': 'in',
'value': ['c22abc43-62f9-4a03-94e0-2a49d0e3c3d8']}}]}]
```
the populated resourceDefinition was in inventory:groups, when our query only pertains to inventory:hosts.
this PR has our code filter out permissions that do not pertain to hosts before analyzing them. This prevents an RBAC result like the one above from causing a …

Ignore non-host RBAC permissions

---

src/roadmap/v1/lifecycle/app_streams.py
tests/v1/lifecycle/test_app_streams.py

Some packages may not have a `:`. Use the partition method to avoid a ValueError and partition on `-` instead.

Properly parse package names that are missing the expected delimiter

---

scripts/freeze.py

This could lead in situations where the system dependencies are added to the requirements.txt files
see https://docs.python.org/3/library/venv.html

Drops `system-site-packages` from freeze script

---

src/roadmap/data/app_streams.py
src/roadmap/models.py
src/roadmap/v1/lifecycle/app_streams.py
tests/test_models.py
tests/utils.py
tests/v1/lifecycle/test_app_streams.py

For RHEL only, a release is considered near retirement when the end date is within three months of the current date.
For app streams, retirement is considered within six months.
I incorrectly set the value to three months for both RHEL and app streams in #181.

[RSPEED-1555] App streams and RHEL have different near retirement values

---

src/roadmap/v1/lifecycle/app_streams.py
tests/v1/lifecycle/test_app_streams.py

Since we are only comparing the package major version, we are picking up a lot of erroneous package entries. Compare using the major and minor version in order to provide accurate results.
While fixing this and looking at the approach to matching a package to an app stream module, I figured out the whole approach is flawed. This does fix the immediate issue but the strategy we are taking to match packages to modules needs to be changed.

[RSPEED-1528] Fully parse NEVRA from package name for more accurate matching

---

scripts/load_host_data.py
tests/conftest.py
tests/v1/lifecycle/test_app_streams.py
tests/v1/lifecycle/test_rhel.py

Get the system IDs by OS version from the test data in order to verify the correct system IDs are returned. I initially was comparing _all_ the system IDs by os version but we have some systems with different lifecycles, so that complicated things. The current tests assert a list of system IDs for one OS version.

[RSPEED-1095] Add tests for relevant APIs

---

src/roadmap/v1/lifecycle/app_streams.py

The end goal is to have one entry in the response per display name. For relevant results that query inventory, the distinction between package and module isn’t helpful, so that was removed from the response.
The fields used to compute the hash for the collection object were pared down to achieve the desired response.
Here are some example response with these changes:
```
name               | display_name                    | application_stream_name     | start_date | end_date   | os_major | os_minor | rolling | count
----------------------------------------------------------------------------------------------------------------------------------------------------
Apache httpd 2.4   | Apache HTTPD 2.4                | Apache httpd 2.4            | 2022-05-18 | 2032-05-31 | 9        | 0 …
```

[RSPEED-1403] Combine module and package results in the relevant response

---

src/roadmap/v1/lifecycle/rhel.py
tests/v1/lifecycle/test_rhel.py

This was a bug by omission. I added a test case to verify the end dates for all lifecycle types are correct.

[RSPEED-1649] Set correct end date for EUS systems

---

.tekton/pipeline-build.yaml

The 0.3 version was working on Friday, but it started failing today. Neither of the 0.3 versions are working but the latest 0.2 version seems to work reliably.

Rollback coverity check to 0.2

---

src/roadmap/data/systems.py

I'm not entirely sure this is correct, but it returns dates instead of Unknown, which allows it to be displayed in the UI.
Officially there does not appear to be EUS or E4S versions of RHEL 8.10, but we definitely have customers with E4S on RHEL 8.10.

[RSPEED-1588] Add EUS and E4S dates for RHEL 8.10 and 9.10

---

src/roadmap/models.py
src/roadmap/v1/lifecycle/app_streams.py
src/roadmap/v1/lifecycle/rhel.py
tests/v1/lifecycle/test_app_streams.py
tests/v1/lifecycle/test_rhel.py

Gather system IDs into a `set` to ensure the values are unique.

[RSPEED-1674] Ensure related system IDs are unique

---

.tekton/pipeline-build.yaml

I had failures with the two latest `sast-coverity-check` images, so I'm using a slightly older 0.3 image. The task failures _seem_ to be a problem with `microdnf` but it's unclean why it's only in the `sast-coverity-check` task that it's a problem. `microdnf` seems to work just fine when building the image outside of coverity.
```
quay.io/konflux-ci/tekton-catalog/task-sast-coverity-check-oci-ta:
quay.io/konflux-ci/tekton-catalog/task-sast-coverity-check-oci-ta:0.3@sha256:f81ade665c725616b918356c8c2fb2d4ed972e822a1a3181933cd0ada728a231  Fri, 27 Jun 2025 14:51:04 -0000
quay.io/konflux-ci/tekton-catalog/task-sast-coverity-check-oci-ta:0.3@sha256:34ac8e9ddfaafedaa61a7c3c95d86e674556bfe3da488d94c3bf28fff9875b38  Thu, 26 Jun 2025 08:51:34 -0000 …
```

Update konflux references

---

scripts/load_host_data.py
src/roadmap/common.py
src/roadmap/v1/lifecycle/app_streams.py
tests/v1/lifecycle/test_app_streams.py

The goal of using a set initially was to keep the number package items that needed to be processed to a minimu. But when system_id was added to the mix, it remove any possibility of deduplicating across systems. Furthermore, this seems to have introduced a bug that causes inconsistent matching of packages to hosts.
Change the grouping strategy to collect system IDs into groups based on the package and its major OS version. I think that gets close to the original goal while still helping improve performance.
I changed the schema of the local hosts table used for development and testing to JSONB fields which matches the production hosts database. Once this change merges, run the following to recreate the host table.
```
make stop-db start-db load-host-data
```

[RSPEED-1515] Change how package data are grouped

---

Containerfile

There are no publicly available rpms of `librepo-1.18.0-5` yet so I had to store it somewhere that could be accessed during the build process.
https://github.com/rpm-software-management/librepo/pull/325

[RSPEED-1730] Update `librepo` to fix intermittent build failure

---

src/roadmap/common.py
src/roadmap/main.py

Add scheme and apply it by default to all APIs. This should add authorization settings to the examples in the API documentation.
https://learn.openapis.org/specification/security.html

[RSPEED-1728] Extend default OpenAPI spec to include API security

---

Containerfile

ubi10-minimal was updated yesterday and includes `librepo-1.18.0-5.el10_0`.
Pin the base image at a specific tag in order to avoid spontaneous breakage.

Remove librepo workaround and pin base image

---

src/roadmap/data/systems.py

The RHEL 7 ELS end date was recently extended.

[RSPEED-1763] Update RHEL 7 ELS end date

---

README.md
scripts/get-redhat-access-token.py

Separate environment variables are used for Prod and Stage tokens. Add a new command line flag, `-e, --env` allows selecting the environment.

Add environment parameter for getting offline token

---

.github/workflows/ci.yml
pyproject.toml

Add configuration for `gha-update` and update actions.
The update to the Coverage action may require configuration changes.

Use `gha-update` to update GitHub actions

---

src/roadmap/data/app_streams.py
src/roadmap/v1/lifecycle/app_streams.py
tests/v1/lifecycle/test_app_streams.py

Add new field `application_stream_type` and add filtering for that field. This is related to changes in #193 and the lifecycle-defs schema changes.

[RSPEED-1816] Add filtering for `application_stream_type`

---

Containerfile

With Python 3.12, it is no longer included by default and we have no need of it for running the application.

Do not install setuptools

---

src/roadmap/common.py
src/roadmap/v1/lifecycle/app_streams.py
src/roadmap/v1/lifecycle/rhel.py
tests/test_common.py
tests/v1/lifecycle/app_streams/test_app_streams_relevant.py

By reducing the amount of data returned from the database, the overall response time is lowered.

[RSPEED-1750] Limit the amount of system profile data returned

---

requirements/requirements-dev-3.12.txt
requirements/requirements-dev-3.13.txt
requirements/requirements-dev.in
requirements/requirements-test-3.12.txt
requirements/requirements-test-3.13.txt
requirements/requirements-test.in
src/roadmap/data/__init__.py
src/roadmap/models.py
src/roadmap/v1/lifecycle/app_streams.py
src/roadmap/v1/lifecycle/rhel.py
src/roadmap/v1/upcoming.py
tests/conftest.py
tests/v1/lifecycle/app_streams/test_app_streams_relevant.py
tests/v1/test_upcoming.py

Create a view of packages by host and use that when matching upcoming items.
Based on the current values, people interpret that field to accept a glob, a comma delimited list of packages, and a proper name of project. The matching right now explicitly compares the literal string values, which will miss a whole lot of matches. This will be addressed in a future change.

[RSPEED-1874] Correct matching for upcoming items

---

src/roadmap/v1/upcoming.py

Adds field_serializiers to UpcomingInput and UpcomingOutput so that the packages set can be sorted during serialization to maintain order.

Sort packages field during serialization
